[v1]
"bandwhich 0.20.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bandwhich"]
"bat 0.18.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"bingrep 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bingrep"]
"bottom 0.6.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"broot 1.7.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["broot"]
"choose 1.3.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["choose"]
"csview 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["csview"]
"desed 1.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["desed"]
"diskonaut 0.11.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["diskonaut"]
"drill 0.7.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["drill"]
"dua-cli 2.14.11 (registry+https://github.com/rust-lang/crates.io-index)" = ["dua"]
"dutree 0.2.18 (registry+https://github.com/rust-lang/crates.io-index)" = ["dutree"]
"exa 0.10.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"fd-find 8.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"fnm 1.28.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["fnm"]
"fselect 0.7.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["fselect"]
"genact 0.11.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["genact"]
"git-delta 0.9.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["delta"]
"git-interactive-rebase-tool 2.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["interactive-rebase-tool"]
"gitui 0.18.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["gitui"]
"glitchcat 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["glitchcat"]
"globe-cli 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["globe"]
"gping 1.2.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["gping"]
"grex 1.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["grex"]
"hexyl 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hexyl"]
"ht 0.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["ht"]
"hyperfine 1.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"lsd 0.20.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["lsd"]
"mcfly 0.5.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["mcfly"]
"monolith 2.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["monolith"]
"nu 0.40.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["nu", "nu_plugin_core_match"]
"oha 0.4.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["oha"]
"onefetch 2.10.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["onefetch"]
"pastel 0.8.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["pastel"]
"procs 0.11.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["procs"]
"ripgrep 13.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"sd 0.7.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["sd"]
"shellharden 4.1.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["shellharden"]
"skim 0.9.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["sk"]
"starship 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["starship"]
"tealdeer 1.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"tmux-thumbs 0.2.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["tmux-thumbs"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"topgrade 8.0.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["topgrade"]
"xsv 0.13.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["xsv"]
"zenith 0.0.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["zenith"]
"zoxide 0.7.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
